version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
       Accept_EULA: "Y"
       SA_PASSWORD: "p@ssword"
       MSSQL_PID: "Express"
    ports:
      - "1433:1433"

